# Joining BasinAtlas data to HUC8 watersheds

In [14]:
import geopandas as gpd
import pandas as pd
from config import *

In [15]:
huc8 = gpd.read_file(geospat_data_filepath+'huc8_shapefiles/HUC8_US_5070.shp')

# Read in basin atlas data
basinatlas = gpd.read_file(INPUT_filepath+'04_static_catchment_characteristics/BasinATLAS_v10_shp/BasinATLAS_v10_lev12.shp')

# clip basin atlas shapefile to just the US
basinatlas_NA = gpd.clip(basinatlas, (-172, 20, -67, 50), keep_geom_type=True)
basinatlas_NA = basinatlas_NA.to_crs(huc8.crs)

In [16]:
# Intersecting the watersheds
basin_intersection = gpd.overlay(basinatlas_NA, 
                                 huc8[['HUC8','AREASQKM','geometry']],
                                 how='intersection')

C:\Users\danyk\AppData\Local\Temp\ipykernel_3044\860978679.py:2: UserWarning: `keep_geom_type=True` in overlay resulted in 1 dropped geometries of different geometry types than df1 has. Set `keep_geom_type=False` to retain all geometries
  basin_intersection = gpd.overlay(basinatlas_NA,

In [17]:
# Calculating the area of the basin atlas watersheds within the HUC8 watershed. 
basin_intersection['partial_area'] = basin_intersection.area / 1e6  # km²

basin_intersection['total_intersected_area'] = (
    basin_intersection.groupby('HUC8')['partial_area'].transform('sum')
)

basin_intersection['weight'] = (
    basin_intersection['partial_area'] / basin_intersection['total_intersected_area']
)
basin_intersection.tail()

,HYBAS_ID,NEXT_DOWN,NEXT_SINK,MAIN_BAS,DIST_SINK,DIST_MAIN,SUB_AREA,UP_AREA,PFAF_ID,ENDO,...,gdp_ud_sav,gdp_ud_ssu,gdp_ud_usu,hdi_ix_sav,HUC8,AREASQKM,geometry,partial_area,total_intersected_area,weight
121427,7120335000,7120340710,7120038320,7120038320,507.3,507.3,207.1,207.2,726087460000,0,...,37544,24123362,24123360,916,01010008,6027.12,"POLYGON ((2011481.092 3065265.29, 2011620.008 ...",202.488624,6027.115758,0.033596
121428,7120982590,7120331560,7120034710,7120034710,26.0,26.0,159.0,159.0,726013062200,0,...,37544,13131531,13131531,916,01010008,6027.12,"MULTIPOLYGON (((2017318.804 3071529.985, 20157...",2.057187,6027.115758,0.000341
121429,7120327310,7120325560,7120034770,7120034770,41.4,41.4,123.5,123.5,726013086000,0,...,37544,5974531,5974532,916,01010008,6027.12,"MULTIPOLYGON (((2029887.331 3076915.56, 202888...",6.710991,6027.115758,0.001113
121430,7120325670,7120323560,7120034770,7120034770,23.9,23.9,155.1,155.1,726013084000,0,...,37544,2889836,2889836,916,01010008,6027.12,"MULTIPOLYGON (((2027228.426 3079608.018, 20272...",0.950501,6027.115758,0.000158
121431,7120980880,7120327210,7120034770,7120034770,52.1,52.1,150.5,620.2,726013087200,0,...,37544,8647379,8849472,916,01010008,6027.12,"MULTIPOLYGON (((2050632.737 3085734.513, 20502...",1.396391,6027.115758,0.000232

In [18]:
# adjusting the variables so they are in their proper (unscaled) units
basin_intersection['ari_ix_sav'] = basin_intersection['ari_ix_sav']/100
basin_intersection['slp_dg_sav'] = basin_intersection['slp_dg_sav']/10

In [19]:
# Use weights to scale the paramteres below
upstream_cols = ['ari_ix_sav', 'kar_pc_sse', 'ppd_pk_sav', 'rdd_mk_sav',
                 'hft_ix_s09', 'slp_dg_sav', 'ele_mt_sav', 'for_pc_sse', 'crp_pc_sse']
majority_cols = ['clz_cl_smj', 'lit_cl_smj']

# Scaling the upstream values based on weights
us_scaled = basin_intersection[upstream_cols].mul(basin_intersection['weight'], axis=0)
us_scaled = pd.concat([basin_intersection['HUC8'], us_scaled], axis=1)
upstream_properties = us_scaled.groupby('HUC8').sum().reset_index()
upstream_properties.head()

,HUC8,ari_ix_sav,kar_pc_sse,ppd_pk_sav,rdd_mk_sav,hft_ix_s09,slp_dg_sav,ele_mt_sav,for_pc_sse,crp_pc_sse
0,01010002,1.317808,0.000000,0.022993,0.330641,3.376571,3.696766,364.239933,94.278009,0.438004
1,01010003,1.288682,0.012400,3.398296,59.318750,30.738986,4.195630,276.806659,88.574380,2.493608
2,01010004,1.234440,26.746052,5.603904,109.398602,46.196095,2.811273,252.189482,91.065739,4.928872
3,01010005,1.216961,23.672741,13.004142,236.298250,76.588309,2.227958,177.873786,92.734520,10.568289
4,01010006,1.379091,0.068268,2.164415,45.532686,25.937524,2.218879,428.012451,97.656674,1.521579

In [27]:
maj = ['clz_cl_smj', 'lit_cl_smj']

# taking the value of the variable's (clim and lith, seperately) class that has the highest coverage in the HUC8 watersehd. 
long = basin_intersection.melt(
    id_vars=['HUC8', 'weight'],
    value_vars=maj,
    var_name='variable', value_name='class'
).dropna(subset=['class'])

dominant_properties = (
    long.groupby(['HUC8', 'variable', 'class'])['weight'].sum()
    .reset_index(name='class_weight')
    .sort_values(['HUC8', 'variable', 'class_weight', 'class'],
                 ascending=[True, True, False, True])
    .groupby(['HUC8', 'variable']).head(1)
    .pivot(index='HUC8', columns='variable', values='class')
    .reset_index()
)
HUC8_properties = upstream_properties.merge(dominant_properties, on = 'HUC8')
HUC8_properties.head()

,HUC8,ari_ix_sav,kar_pc_sse,ppd_pk_sav,rdd_mk_sav,hft_ix_s09,slp_dg_sav,ele_mt_sav,for_pc_sse,crp_pc_sse,clz_cl_smj,lit_cl_smj
0,01010002,1.317808,0.000000,0.022993,0.330641,3.376571,3.696766,364.239933,94.278009,0.438004,7,3
1,01010003,1.288682,0.012400,3.398296,59.318750,30.738986,4.195630,276.806659,88.574380,2.493608,7,3
2,01010004,1.234440,26.746052,5.603904,109.398602,46.196095,2.811273,252.189482,91.065739,4.928872,7,3
3,01010005,1.216961,23.672741,13.004142,236.298250,76.588309,2.227958,177.873786,92.734520,10.568289,7,6
4,01010006,1.379091,0.068268,2.164415,45.532686,25.937524,2.218879,428.012451,97.656674,1.521579,7,3

In [28]:
HUC8_properties.dtypes

HUC8           object
ari_ix_sav    float64
kar_pc_sse    float64
ppd_pk_sav    float64
rdd_mk_sav    float64
hft_ix_s09    float64
slp_dg_sav    float64
ele_mt_sav    float64
for_pc_sse    float64
crp_pc_sse    float64
clz_cl_smj      int32
lit_cl_smj      int32
dtype: object

## Adding NLCD Land use

In [22]:
NLCD_landcover = pd.read_csv(INPUT_filepath+'04_static_catchment_characteristics/HUC8_NLCD_LandCover_Pct_1985_2024.csv',
                             dtype={"HUC8": str})

NLCD_landcover.head()

,HUC8,year,pct_11,pct_12,pct_21,pct_22,pct_23,pct_24,pct_31,pct_41,pct_42,pct_43,pct_52,pct_71,pct_81,pct_82,pct_90,pct_95
0,01010004,1985,1.749310,0.0,1.227430,1.063832,0.198251,0.063040,0.097148,8.793501,20.967065,34.267702,1.530072,2.672842,2.124058,7.441909,17.453609,0.350231
1,01010005,1985,0.931609,0.0,1.852087,1.567600,0.244920,0.067566,0.166346,10.083908,12.725280,34.047453,1.201230,1.360553,5.254385,9.839412,20.454218,0.203434
2,01010010,1985,0.494848,0.0,2.028351,2.037052,0.217031,0.053693,0.052221,12.773728,3.287137,22.626948,0.584419,0.392891,8.222835,26.247952,20.534460,0.446434
3,01040001,1985,6.554279,0.0,1.073068,0.609338,0.128681,0.029839,0.091416,31.615267,27.131248,21.087105,1.024919,2.704472,0.245899,0.006493,7.526135,0.171840
4,04070001,1985,17.177688,0.0,2.105395,1.601276,0.453645,0.113832,0.459043,8.050076,6.483145,9.727336,0.483386,1.634020,14.194966,1.631662,34.269361,1.615169

In [23]:
mean_NLCD_landcover = NLCD_landcover.groupby(by=['HUC8']).mean().reset_index()
mean_NLCD_landcover = mean_NLCD_landcover.drop(['year'], axis=1)

mean_NLCD_landcover.head()

,HUC8,pct_11,pct_12,pct_21,pct_22,pct_23,pct_24,pct_31,pct_41,pct_42,pct_43,pct_52,pct_71,pct_81,pct_82,pct_90,pct_95
0,01010002,4.128765,0.0,0.843090,0.609890,0.013230,0.000028,0.017251,15.940846,28.215786,32.683131,7.003886,4.158481,0.003338,0.000908,6.051108,0.330262
1,01010003,6.223677,0.0,1.275009,0.961177,0.121125,0.010136,0.095107,16.657652,14.535792,33.961202,4.194332,2.970783,2.564499,3.028597,12.977963,0.422949
2,01010004,1.759143,0.0,1.485761,1.219359,0.210008,0.068698,0.107276,9.105636,18.103061,33.443691,4.176238,2.578928,3.042332,6.414160,17.890319,0.395390
3,01010005,0.929382,0.0,1.966930,1.735505,0.286611,0.076276,0.190687,10.283040,9.148503,33.807376,3.336092,2.032776,6.394150,8.537988,21.008033,0.266651
4,01010006,1.094613,0.0,0.689448,0.584671,0.014096,0.000000,0.039736,14.020605,40.703632,19.112552,7.706868,4.053401,0.001219,0.000334,11.397217,0.581608

In [24]:
nlcd_shortnames = {
    "pct_11": "pct_open_water",
    "pct_12": "pct_perennial_ice_snow",
    "pct_21": "pct_developed_open",
    "pct_22": "pct_developed_low",
    "pct_23": "pct_developed_med",
    "pct_24": "pct_developed_high",
    "pct_31": "pct_barren",
    "pct_41": "pct_deciduous_forest",
    "pct_42": "pct_evergreen_forest",
    "pct_43": "pct_mixed_forest",
    "pct_51": "pct_dwarf_scrub",
    "pct_52": "pct_shrub_scrub",
    "pct_71": "pct_grassland",
    "pct_72": "pct_sedge",
    "pct_73": "pct_lichens",
    "pct_74": "pct_moss",
    "pct_81": "pct_pasture_hay",
    "pct_82": "pct_cultivated_crops",
    "pct_90": "pct_woody_wetlands",
    "pct_95": "pct_emergent_wetlands",
}

mean_NLCD_landcover = mean_NLCD_landcover.rename(columns=nlcd_shortnames)

In [29]:
HUC8_properties = HUC8_properties.merge(mean_NLCD_landcover, on='HUC8')
HUC8_properties.to_csv(INPUT_filepath+'04_static_catchment_characteristics/huc8_basinatlas_properties.csv', index=False)
HUC8_properties.head()

,HUC8,ari_ix_sav,kar_pc_sse,ppd_pk_sav,rdd_mk_sav,hft_ix_s09,slp_dg_sav,ele_mt_sav,for_pc_sse,crp_pc_sse,...,pct_barren,pct_deciduous_forest,pct_evergreen_forest,pct_mixed_forest,pct_shrub_scrub,pct_grassland,pct_pasture_hay,pct_cultivated_crops,pct_woody_wetlands,pct_emergent_wetlands
0,01010002,1.317808,0.000000,0.022993,0.330641,3.376571,3.696766,364.239933,94.278009,0.438004,...,0.017251,15.940846,28.215786,32.683131,7.003886,4.158481,0.003338,0.000908,6.051108,0.330262
1,01010003,1.288682,0.012400,3.398296,59.318750,30.738986,4.195630,276.806659,88.574380,2.493608,...,0.095107,16.657652,14.535792,33.961202,4.194332,2.970783,2.564499,3.028597,12.977963,0.422949
2,01010004,1.234440,26.746052,5.603904,109.398602,46.196095,2.811273,252.189482,91.065739,4.928872,...,0.107276,9.105636,18.103061,33.443691,4.176238,2.578928,3.042332,6.414160,17.890319,0.395390
3,01010005,1.216961,23.672741,13.004142,236.298250,76.588309,2.227958,177.873786,92.734520,10.568289,...,0.190687,10.283040,9.148503,33.807376,3.336092,2.032776,6.394150,8.537988,21.008033,0.266651
4,01010006,1.379091,0.068268,2.164415,45.532686,25.937524,2.218879,428.012451,97.656674,1.521579,...,0.039736,14.020605,40.703632,19.112552,7.706868,4.053401,0.001219,0.000334,11.397217,0.581608